INSERT INTO state (name) VALUES ('Acre');
INSERT INTO city (name, state_id) VALUES ('Rio Branco', 1);
INSERT INTO state (name) VALUES ('Alagoas');
INSERT INTO city (name, state_id) VALUES ('Maceió', 2);
INSERT INTO state (name) VALUES ('Amapá');
INSERT INTO city (name, state_id) VALUES ('Macapá', 3);
INSERT INTO state (name) VALUES ('Amazonas');
INSERT INTO city (name, state_id) VALUES ('Manaus', 4);
INSERT INTO state (name) VALUES ('Bahia');
INSERT INTO city (name, state_id) VALUES ('Salvador', 5);
INSERT INTO state (name) VALUES ('Ceará');
INSERT INTO city (name, state_id) VALUES ('Fortaleza', 6);
INSERT INTO state (name) VALUES ('Distrito Federal');
INSERT INTO city (name, state_id) VALUES ('Brasília', 7);
INSERT INTO state (name) VALUES ('Espírito Santo');
INSERT INTO city (name, state_id) VALUES ('Vitória', 8);
INSERT INTO state (name) VALUES ('Goiás');
INSERT INTO city (name, state_id) VALUES ('Goiânia', 9);
INSERT INTO state (name) VALUES ('Maranhão');
INSERT INTO city (name, state_id) VALUES ('São Luís', 10);
INSERT INTO state (name) VALUES ('Mato Grosso');
INSERT INTO city (name, state_id) VALUES ('Cuiabá', 11);
INSERT INTO state (name) VALUES ('Mato Grosso do Sul');
INSERT INTO city (name, state_id) VALUES ('Campo Grande', 12);
INSERT INTO state (name) VALUES ('Minas Gerais');
INSERT INTO city (name, state_id) VALUES ('Belo Horizonte', 13);
INSERT INTO state (name) VALUES ('Pará');
INSERT INTO city (name, state_id) VALUES ('Belém', 14);
INSERT INTO state (name) VALUES ('Paraíba');
INSERT INTO city (name, state_id) VALUES ('João Pessoa', 15);
INSERT INTO state (name) VALUES ('Paraná');
INSERT INTO city (name, state_id) VALUES ('Curitiba', 16);
INSERT INTO state (name) VALUES ('Pernambuco');
INSERT INTO city (name, state_id) VALUES ('Recife', 17);
INSERT INTO state (name) VALUES ('Piauí');
INSERT INTO city (name, state_id) VALUES ('Recife', 18);
INSERT INTO state (name) VALUES ('Rio de Janeiro');
INSERT INTO city (name, state_id) VALUES ('Rio de Janeiro', 19);
INSERT INTO state (name) VALUES ('Rio Grande do Norte');
INSERT INTO city (name, state_id) VALUES ('Natal', 20);
INSERT INTO state (name) VALUES ('Rio Grande do Sul');
INSERT INTO city (name, state_id) VALUES ('Porto Alegre', 21);
INSERT INTO state (name) VALUES ('Rondônia');
INSERT INTO city (name, state_id) VALUES ('Porto Velho', 22);
INSERT INTO state (name) VALUES ('Roraima');
INSERT INTO city (name, state_id) VALUES ('Boa Vista', 23);
INSERT INTO state (name) VALUES ('Santa Catarina');
INSERT INTO city (name, state_id) VALUES ('Florianópolis', 24);
INSERT INTO state (name) VALUES ('São Paulo');
INSERT INTO city (name, state_id) VALUES ('São Paulo', 25);
INSERT INTO state (name) VALUES ('Sergipe');
INSERT INTO city (name, state_id) VALUES ('Aracaju', 26);
INSERT INTO state (name) VALUES ('Tocantins');
INSERT INTO city (name, state_id) VALUES ('Palmas', 27);