CREATE TABLE `order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sub_total` decimal(38,2) NOT NULL,
  `ship_rate` decimal(38,2) NOT NULL,
  `total_value` decimal(38,2) NOT NULL,
  `creation_date` datetime NOT NULL,
  `confirmation_date` datetime DEFAULT NULL,
  `cancellation_date` datetime DEFAULT NULL,
  `delivery_date` datetime DEFAULT NULL,
  `restaurant_id` bigint NOT NULL,
  `customer_id` bigint NOT NULL,
  `payment_method_id` bigint NOT NULL,
  `address_street_or_avenue` varchar(255) NOT NULL,
  `address_number` varchar(255) NOT NULL,
  `address_complement` varchar(255) DEFAULT NULL,
  `address_neighborhood` varchar(255) NOT NULL,
  `address_zip_code` varchar(255) NOT NULL,
  `address_city_id` bigint NOT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `restaurant_fk_3` (`restaurant_id`),
  KEY `customer_fk_1` (`customer_id`),
  KEY `payment_method_fk_2` (`payment_method_id`),
  KEY `address_city_fk_2` (`address_city_id`),
  CONSTRAINT `restaurant_fk_3` FOREIGN KEY (`restaurant_id`) REFERENCES `restaurant` (`id`),
  CONSTRAINT `customer_fk_1` FOREIGN KEY (`customer_id`) REFERENCES `user` (`id`),
  CONSTRAINT `payment_method_fk_2` FOREIGN KEY (`payment_method_id`) REFERENCES `payment_method` (`id`),
  CONSTRAINT `address_city_fk_2` FOREIGN KEY (`address_city_id`) REFERENCES `city` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci